-- Fix PaymentReceipts / RecurringInvoices Id columns missing PostgreSQL identity.
-- Root cause: SQLite-oriented migrations created Id as plain integer NOT NULL with no default.
-- EF inserts then fail with: 23502 null value in column "Id" of relation "PaymentReceipts".
-- Also converts RecurringInvoices.IsActive from integer → boolean to match the C# model.
--
-- RunSql splits on ';' — keep each ALTER as its own statement (no DO $$ blocks).
-- Prefer app startup DO $$ (Program.cs) on Render deploy; use this for manual RunSql apply.
-- Re-running ADD GENERATED after identity exists will error — that is expected.

ALTER TABLE "PaymentReceipts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "RecurringInvoices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "RecurringInvoiceItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "RecurringInvoices" ALTER COLUMN "IsActive" DROP DEFAULT;
ALTER TABLE "RecurringInvoices" ALTER COLUMN "IsActive" TYPE boolean USING (CASE WHEN "IsActive"::int = 0 THEN false ELSE true END);
ALTER TABLE "RecurringInvoices" ALTER COLUMN "IsActive" SET DEFAULT true;
