-- NOTE: This script is designed for the simple RunSql runner, which splits on ';'
-- so it must contain a single statement (no DO $$ blocks).
-- Run once only. If you run it again after the identity is already present,
-- PostgreSQL will raise an error.

ALTER TABLE "VatReturnPeriods"
    ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
