using HexaBill.Api.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HexaBill.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260927190000_AddBackupAgentDevices")]
public partial class AddBackupAgentDevices : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""BackupDevices"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""TenantId"" integer NOT NULL,
    ""CreatedByUserId"" integer NOT NULL,
    ""DisplayName"" character varying(80) NOT NULL,
    ""FolderLabel"" character varying(120) NULL,
    ""LastSeenAt"" timestamp with time zone NULL,
    ""RevokedAt"" timestamp with time zone NULL,
    ""AgentVersion"" character varying(40) NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_BackupDevices"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_BackupDevices_Tenants_TenantId"" FOREIGN KEY (""TenantId"") REFERENCES ""Tenants"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_BackupDevices_Users_CreatedByUserId"" FOREIGN KEY (""CreatedByUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS ""IX_BackupDevices_TenantId"" ON ""BackupDevices"" (""TenantId"");
CREATE INDEX IF NOT EXISTS ""IX_BackupDevices_CreatedByUserId"" ON ""BackupDevices"" (""CreatedByUserId"");

CREATE TABLE IF NOT EXISTS ""BackupDeviceSchedules"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""TenantId"" integer NOT NULL,
    ""DeviceId"" integer NOT NULL,
    ""Enabled"" boolean NOT NULL,
    ""Frequency"" character varying(16) NOT NULL,
    ""LocalTime"" character varying(5) NOT NULL,
    ""TimeZoneId"" character varying(80) NOT NULL,
    ""WeeklyDay"" integer NOT NULL,
    ""IncludeInvoicePdfs"" boolean NOT NULL,
    ""RetentionCount"" integer NOT NULL,
    ""UpdatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_BackupDeviceSchedules"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_BackupDeviceSchedules_BackupDevices_DeviceId"" FOREIGN KEY (""DeviceId"") REFERENCES ""BackupDevices"" (""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_BackupDeviceSchedules_Tenants_TenantId"" FOREIGN KEY (""TenantId"") REFERENCES ""Tenants"" (""Id"") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_BackupDeviceSchedules_DeviceId"" ON ""BackupDeviceSchedules"" (""DeviceId"");
CREATE INDEX IF NOT EXISTS ""IX_BackupDeviceSchedules_TenantId"" ON ""BackupDeviceSchedules"" (""TenantId"");

CREATE TABLE IF NOT EXISTS ""BackupDeviceTokens"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""TenantId"" integer NOT NULL,
    ""DeviceId"" integer NOT NULL,
    ""TokenHash"" character varying(64) NOT NULL,
    ""ExpiresAt"" timestamp with time zone NOT NULL,
    ""RevokedAt"" timestamp with time zone NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_BackupDeviceTokens"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_BackupDeviceTokens_BackupDevices_DeviceId"" FOREIGN KEY (""DeviceId"") REFERENCES ""BackupDevices"" (""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_BackupDeviceTokens_Tenants_TenantId"" FOREIGN KEY (""TenantId"") REFERENCES ""Tenants"" (""Id"") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_BackupDeviceTokens_TokenHash"" ON ""BackupDeviceTokens"" (""TokenHash"");
CREATE INDEX IF NOT EXISTS ""IX_BackupDeviceTokens_DeviceId"" ON ""BackupDeviceTokens"" (""DeviceId"");

CREATE TABLE IF NOT EXISTS ""BackupPairingCodes"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""TenantId"" integer NOT NULL,
    ""CreatedByUserId"" integer NOT NULL,
    ""CodeHash"" character varying(64) NOT NULL,
    ""ExpiresAt"" timestamp with time zone NOT NULL,
    ""ConsumedAt"" timestamp with time zone NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_BackupPairingCodes"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_BackupPairingCodes_Tenants_TenantId"" FOREIGN KEY (""TenantId"") REFERENCES ""Tenants"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_BackupPairingCodes_Users_CreatedByUserId"" FOREIGN KEY (""CreatedByUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_BackupPairingCodes_CodeHash"" ON ""BackupPairingCodes"" (""CodeHash"");
CREATE INDEX IF NOT EXISTS ""IX_BackupPairingCodes_TenantId"" ON ""BackupPairingCodes"" (""TenantId"");
CREATE INDEX IF NOT EXISTS ""IX_BackupPairingCodes_CreatedByUserId"" ON ""BackupPairingCodes"" (""CreatedByUserId"");

CREATE TABLE IF NOT EXISTS ""BackupRuns"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""TenantId"" integer NOT NULL,
    ""DeviceId"" integer NOT NULL,
    ""SlotKey"" character varying(16) NOT NULL,
    ""Status"" character varying(20) NOT NULL,
    ""SizeBytes"" bigint NULL,
    ""Sha256"" character varying(64) NULL,
    ""Verified"" boolean NOT NULL,
    ""MissedCatchUp"" boolean NOT NULL,
    ""FailureReason"" character varying(200) NULL,
    ""FileName"" character varying(180) NULL,
    ""DownloadName"" character varying(180) NULL,
    ""StartedAt"" timestamp with time zone NOT NULL,
    ""CompletedAt"" timestamp with time zone NULL,
    CONSTRAINT ""PK_BackupRuns"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_BackupRuns_BackupDevices_DeviceId"" FOREIGN KEY (""DeviceId"") REFERENCES ""BackupDevices"" (""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_BackupRuns_Tenants_TenantId"" FOREIGN KEY (""TenantId"") REFERENCES ""Tenants"" (""Id"") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_BackupRuns_DeviceId_SlotKey"" ON ""BackupRuns"" (""DeviceId"", ""SlotKey"");
CREATE INDEX IF NOT EXISTS ""IX_BackupRuns_TenantId"" ON ""BackupRuns"" (""TenantId"");
");
            return;
        }

        migrationBuilder.CreateTable(
            name: "BackupDevices",
            columns: table => new
            {
                Id = table.Column<int>(type: "INTEGER", nullable: false).Annotation("Sqlite:Autoincrement", true),
                TenantId = table.Column<int>(type: "INTEGER", nullable: false),
                CreatedByUserId = table.Column<int>(type: "INTEGER", nullable: false),
                DisplayName = table.Column<string>(type: "TEXT", maxLength: 80, nullable: false),
                FolderLabel = table.Column<string>(type: "TEXT", maxLength: 120, nullable: true),
                LastSeenAt = table.Column<DateTime>(type: "TEXT", nullable: true),
                RevokedAt = table.Column<DateTime>(type: "TEXT", nullable: true),
                AgentVersion = table.Column<string>(type: "TEXT", maxLength: 40, nullable: true),
                CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_BackupDevices", x => x.Id);
                table.ForeignKey("FK_BackupDevices_Tenants_TenantId", x => x.TenantId, "Tenants", "Id", onDelete: ReferentialAction.Restrict);
                table.ForeignKey("FK_BackupDevices_Users_CreatedByUserId", x => x.CreatedByUserId, "Users", "Id", onDelete: ReferentialAction.Restrict);
            });
        migrationBuilder.CreateIndex("IX_BackupDevices_TenantId", "BackupDevices", "TenantId");
        migrationBuilder.CreateIndex("IX_BackupDevices_CreatedByUserId", "BackupDevices", "CreatedByUserId");

        migrationBuilder.CreateTable(
            name: "BackupDeviceSchedules",
            columns: table => new
            {
                Id = table.Column<int>(type: "INTEGER", nullable: false).Annotation("Sqlite:Autoincrement", true),
                TenantId = table.Column<int>(type: "INTEGER", nullable: false),
                DeviceId = table.Column<int>(type: "INTEGER", nullable: false),
                Enabled = table.Column<bool>(type: "INTEGER", nullable: false),
                Frequency = table.Column<string>(type: "TEXT", maxLength: 16, nullable: false),
                LocalTime = table.Column<string>(type: "TEXT", maxLength: 5, nullable: false),
                TimeZoneId = table.Column<string>(type: "TEXT", maxLength: 80, nullable: false),
                WeeklyDay = table.Column<int>(type: "INTEGER", nullable: false),
                IncludeInvoicePdfs = table.Column<bool>(type: "INTEGER", nullable: false),
                RetentionCount = table.Column<int>(type: "INTEGER", nullable: false),
                UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_BackupDeviceSchedules", x => x.Id);
                table.ForeignKey("FK_BackupDeviceSchedules_BackupDevices_DeviceId", x => x.DeviceId, "BackupDevices", "Id", onDelete: ReferentialAction.Cascade);
                table.ForeignKey("FK_BackupDeviceSchedules_Tenants_TenantId", x => x.TenantId, "Tenants", "Id", onDelete: ReferentialAction.Restrict);
            });
        migrationBuilder.CreateIndex("IX_BackupDeviceSchedules_DeviceId", "BackupDeviceSchedules", "DeviceId", unique: true);
        migrationBuilder.CreateIndex("IX_BackupDeviceSchedules_TenantId", "BackupDeviceSchedules", "TenantId");

        migrationBuilder.CreateTable(
            name: "BackupDeviceTokens",
            columns: table => new
            {
                Id = table.Column<int>(type: "INTEGER", nullable: false).Annotation("Sqlite:Autoincrement", true),
                TenantId = table.Column<int>(type: "INTEGER", nullable: false),
                DeviceId = table.Column<int>(type: "INTEGER", nullable: false),
                TokenHash = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                ExpiresAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                RevokedAt = table.Column<DateTime>(type: "TEXT", nullable: true),
                CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_BackupDeviceTokens", x => x.Id);
                table.ForeignKey("FK_BackupDeviceTokens_BackupDevices_DeviceId", x => x.DeviceId, "BackupDevices", "Id", onDelete: ReferentialAction.Cascade);
                table.ForeignKey("FK_BackupDeviceTokens_Tenants_TenantId", x => x.TenantId, "Tenants", "Id", onDelete: ReferentialAction.Restrict);
            });
        migrationBuilder.CreateIndex("IX_BackupDeviceTokens_TokenHash", "BackupDeviceTokens", "TokenHash", unique: true);
        migrationBuilder.CreateIndex("IX_BackupDeviceTokens_DeviceId", "BackupDeviceTokens", "DeviceId");

        migrationBuilder.CreateTable(
            name: "BackupPairingCodes",
            columns: table => new
            {
                Id = table.Column<int>(type: "INTEGER", nullable: false).Annotation("Sqlite:Autoincrement", true),
                TenantId = table.Column<int>(type: "INTEGER", nullable: false),
                CreatedByUserId = table.Column<int>(type: "INTEGER", nullable: false),
                CodeHash = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                ExpiresAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                ConsumedAt = table.Column<DateTime>(type: "TEXT", nullable: true),
                CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_BackupPairingCodes", x => x.Id);
                table.ForeignKey("FK_BackupPairingCodes_Tenants_TenantId", x => x.TenantId, "Tenants", "Id", onDelete: ReferentialAction.Restrict);
                table.ForeignKey("FK_BackupPairingCodes_Users_CreatedByUserId", x => x.CreatedByUserId, "Users", "Id", onDelete: ReferentialAction.Restrict);
            });
        migrationBuilder.CreateIndex("IX_BackupPairingCodes_CodeHash", "BackupPairingCodes", "CodeHash", unique: true);
        migrationBuilder.CreateIndex("IX_BackupPairingCodes_TenantId", "BackupPairingCodes", "TenantId");
        migrationBuilder.CreateIndex("IX_BackupPairingCodes_CreatedByUserId", "BackupPairingCodes", "CreatedByUserId");

        migrationBuilder.CreateTable(
            name: "BackupRuns",
            columns: table => new
            {
                Id = table.Column<int>(type: "INTEGER", nullable: false).Annotation("Sqlite:Autoincrement", true),
                TenantId = table.Column<int>(type: "INTEGER", nullable: false),
                DeviceId = table.Column<int>(type: "INTEGER", nullable: false),
                SlotKey = table.Column<string>(type: "TEXT", maxLength: 16, nullable: false),
                Status = table.Column<string>(type: "TEXT", maxLength: 20, nullable: false),
                SizeBytes = table.Column<long>(type: "INTEGER", nullable: true),
                Sha256 = table.Column<string>(type: "TEXT", maxLength: 64, nullable: true),
                Verified = table.Column<bool>(type: "INTEGER", nullable: false),
                MissedCatchUp = table.Column<bool>(type: "INTEGER", nullable: false),
                FailureReason = table.Column<string>(type: "TEXT", maxLength: 200, nullable: true),
                FileName = table.Column<string>(type: "TEXT", maxLength: 180, nullable: true),
                DownloadName = table.Column<string>(type: "TEXT", maxLength: 180, nullable: true),
                StartedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                CompletedAt = table.Column<DateTime>(type: "TEXT", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_BackupRuns", x => x.Id);
                table.ForeignKey("FK_BackupRuns_BackupDevices_DeviceId", x => x.DeviceId, "BackupDevices", "Id", onDelete: ReferentialAction.Cascade);
                table.ForeignKey("FK_BackupRuns_Tenants_TenantId", x => x.TenantId, "Tenants", "Id", onDelete: ReferentialAction.Restrict);
            });
        migrationBuilder.CreateIndex("IX_BackupRuns_DeviceId_SlotKey", "BackupRuns", new[] { "DeviceId", "SlotKey" }, unique: true);
        migrationBuilder.CreateIndex("IX_BackupRuns_TenantId", "BackupRuns", "TenantId");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable("BackupRuns");
        migrationBuilder.DropTable("BackupPairingCodes");
        migrationBuilder.DropTable("BackupDeviceTokens");
        migrationBuilder.DropTable("BackupDeviceSchedules");
        migrationBuilder.DropTable("BackupDevices");
    }
}
