using HexaBill.Api.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HexaBill.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260927080000_AddTenantVatCalculationBasis")]
public partial class AddTenantVatCalculationBasis : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
        {
            migrationBuilder.Sql(@"ALTER TABLE ""Tenants"" ADD COLUMN IF NOT EXISTS ""VatCalculationBasis"" character varying(20) NOT NULL DEFAULT 'SalesBased';");
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""TenantVatBasisHistory"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""TenantId"" integer NOT NULL,
    ""Basis"" character varying(20) NOT NULL,
    ""EffectiveFrom"" timestamp with time zone NOT NULL,
    ""SetByUserId"" integer NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_TenantVatBasisHistory"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_TenantVatBasisHistory_Tenants_TenantId"" FOREIGN KEY (""TenantId"") REFERENCES ""Tenants"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_TenantVatBasisHistory_Users_SetByUserId"" FOREIGN KEY (""SetByUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
);");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_TenantVatBasisHistory_TenantId_EffectiveFrom"" ON ""TenantVatBasisHistory"" (""TenantId"", ""EffectiveFrom"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_TenantVatBasisHistory_SetByUserId"" ON ""TenantVatBasisHistory"" (""SetByUserId"");");
            return;
        }

        migrationBuilder.AddColumn<string>(
            name: "VatCalculationBasis",
            table: "Tenants",
            type: "TEXT",
            maxLength: 20,
            nullable: false,
            defaultValue: "SalesBased");

        migrationBuilder.CreateTable(
            name: "TenantVatBasisHistory",
            columns: table => new
            {
                Id = table.Column<int>(type: "INTEGER", nullable: false)
                    .Annotation("Sqlite:Autoincrement", true),
                TenantId = table.Column<int>(type: "INTEGER", nullable: false),
                Basis = table.Column<string>(type: "TEXT", maxLength: 20, nullable: false),
                EffectiveFrom = table.Column<DateTime>(type: "TEXT", nullable: false),
                SetByUserId = table.Column<int>(type: "INTEGER", nullable: false),
                CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_TenantVatBasisHistory", x => x.Id);
                table.ForeignKey("FK_TenantVatBasisHistory_Tenants_TenantId", x => x.TenantId, "Tenants", "Id", onDelete: ReferentialAction.Restrict);
                table.ForeignKey("FK_TenantVatBasisHistory_Users_SetByUserId", x => x.SetByUserId, "Users", "Id", onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateIndex(
            name: "IX_TenantVatBasisHistory_TenantId_EffectiveFrom",
            table: "TenantVatBasisHistory",
            columns: new[] { "TenantId", "EffectiveFrom" });

        migrationBuilder.CreateIndex(
            name: "IX_TenantVatBasisHistory_SetByUserId",
            table: "TenantVatBasisHistory",
            column: "SetByUserId");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable("TenantVatBasisHistory");
        migrationBuilder.DropColumn("VatCalculationBasis", "Tenants");
    }
}
